version: '3.6'

services: 
    web:
        build: .
        command: python /bookstore_project/manage.py runserver 0.0.0.0:8000
        environment: 
            - SECRET_KEY=l_o7oi1rg5)t^lxm9-43%0)s-=1qpeq%o7gfq+e5#*!t+_ev80
            - DEBUG=1
        volumes: 
            - .:/bookstore_project
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: postgres
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
volumes: 
    postgres_data: