version: '3.6'

services: 
    web:
        build: .
        command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
        environment: 
            - ENVIRONMENT=development
            - SECRET_KEY=<secret key for django>
            - DEBUG=1
            - STRIPE_TEST_PUBLISHABLE_KEY=<publish key stripe>
            - STRIPE_TEST_SECRET_KEY=<secret key stripe>
        volumes: 
            - .:/bookstore_project
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: postgres
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
volumes: 
    postgres_data: